### ISSUE TITLE
Wayland protocol integration

### ISSUE THREAD

**Issue by breznak** [maandree/cg-tools#2]
As we discussed in redshift https://github.com/jonls/redshift/issues/574 , you suggest `libcoopgamma` as a common solution. Would it then make sense to try to integrate the color/gamma management in Wayland, which each compositor currently has to implement themselves. 
It seems this could be done as wayland protocol extension: https://github.com/wayland-project/wayland-protocols

**Comment by maandree** [comment]
I would suggest reimplementing coopgammad into the compositors, and add colour space manipulation support, and then extend libcoopgamma to support it.

Another option is to just add a simple gamma protocol, like the ones found in current display servers, and extend libgamma to support it, and let coopgammad do rest of work. However, this option would not allow you do to colour space manipulation, just gamma ramp manipulation.

Adding colour space manipulation support is useful because it lets you do things like greyscale mode that just suggested and simulate defective colour vision so you can test the accessibility of your interfaces.
